# Generated by Django 4.1.6 on 2023-05-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_disc', models.CharField(max_length=255)),
                ('item_price', models.FloatField()),
                ('img', models.CharField(max_length=255)),
            ],
        ),
    ]
