# Generated by Django 4.1.6 on 2023-05-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.CharField(max_length=255),
        ),
    ]
